Routes:
  - 
     InstanceName: "instance-name1"
     AmqpHost: "192.168.99.100"
     AmqpUser: "guest"
     AmqpPassword: "guest"
     AmqpQueue: "rpc_queue"
     AmqpPrefetchCount: 5
     FcgiHost: "192.168.99.100:9000"
     FcgiTimeout: 5
     FcgiServerProtocol: "HTTP/1.1"
     FcgiScriptName: "/app/process.php"
     FcgiScriptFilename: "/app/process.php"
     FcgiRequestUri: "/app/process.php/job/process"
  - 
     InstanceName: "instance-name2"
     AmqpHost: "192.168.99.100"
     AmqpUser: "guest"
     AmqpPassword: "guest"
     AmqpQueue: "rpc_queue"
     AmqpPrefetchCount: 5
     FcgiHost: "192.168.99.100:9000"
     FcgiTimeout: 5
     FcgiServerProtocol: "HTTP/1.1"
     FcgiScriptName: "/app/process.php"
     FcgiScriptFilename: "/app/process.php"
     FcgiRequestUri: "/app/process.php/job/process"