Brokers:
 -
     Id: "main"
     Type: "rabbitmq"
     Host: "192.168.99.100"
     User: "guest"
     Password: "guest"
     
     
Workers:
 -
     Id: "mainworker"
     Type: "fastcgi"
     Host: "192.168.99.100:9000"
     Timeout: 5
     ServerProtocol: "HTTP/1.1"
     ScriptName: "/app/process.php"
     ScriptFilename: "/app/process.php"
     RequestUri: "/app/process.php/job/process"
     
Routes:
 -
     Name: "rpc-main" # NOTE! domain-like unique name, used as SERVER_NAME fcgi parameter 
     Broker: "main"
     Worker: "mainworker"
     Queue: "rpc_queue"
     PrefetchCount: 5
